services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant

  fastapi_v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    ports:
      - "8001:8001"
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
    command: >
      bash -c "cd lore_v2 && uvicorn main_v2:app --host 0.0.0.0 --port 8001"
